name: e2e

on:
  push:
    branches:
      - master

jobs:
  test-e2e:
    name: RUN E2E tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "20"  # Use Node.js version 20

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps  # Install Playwright browsers with dependencies

      - name: Run your tests
        run: npx playwright test tests/css.spec.ts  # Run Playwright tests

      - name: Upload test results
        if: always()  # Always upload test results, even if the tests fail
        uses: actions/upload-artifact@v2  # Corrected action name
        with:
          name: Test Result  # The name for the uploaded artifact
          path: test-results  # Path to test results (make sure this folder exists)