name: e2e

on:
  push:
    branches:
      - master

jobs:
  test-e2e:
    name: RUN E2E tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: "20"  # Use Node.js version 20

      # Clear cache (if needed)
      - name: Clear npm cache
        run: |
          rm -rf ~/.npm  # Removes the npm cache
          rm -rf node_modules  # Removes node_modules if you want to ensure a fresh install

      # Install dependencies and Playwright
      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps  # Install Playwright browsers with dependencies

      # Run Playwright tests and generate HTML report
      - name: Run your tests
        run: npx playwright test tests/css.spec.ts --reporter=html  # Run Playwright tests

      # Upload test results as an artifact
      - name: Upload test results
        if: always()  # Always upload test results, even if the tests fail
        uses: actions/upload-artifact@v3  # Corrected action name
        with:
          name: Test Result  # The name for the uploaded artifact
          path: playwright-report  # Corrected path to the Playwright report folder