name: e2e

on:
  push:
    branches:
      - master

jobs:
  test-e2e:
    name: RUN E2E tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip libnss3 libgdk-pixbuf2.0-0 libx11-xcb1

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --force --with-deps

      - name: Check Chromium Download URL
        run: curl -I https://playwright.download.prss.microsoft.com/dbazure/download/playwright/builds/chromium/1161/chromium-linux.zip

      - name: Run your tests
        run: npx playwright test tests/css.spec.ts --reporter=html