name: e2e

on:
  push:
    branches:
      - master

jobs:
  test-e2e:
    name: RUN E2E tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: "20"  # Use Node.js version 20
      # Install dependencies and Playwright
      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps  # Install Playwright browsers with dependencies

      # Run Playwright tests and generate HTML report
      - name: Run Home page tests
        run: npx playwright test demoPOM.spec.ts
      # - name: Run Search page Project  
      #   run: npx playwright test demoSearch.spec.ts --reporter=html 
      # - name: Run For the availabe tabs with the link
      #   run: npx playwright test demoSearchTabs.spec.ts --reporter=html
      # - name: Run For the rank table 
      #   run: npx playwright test demoRankingTable.spec.ts --reporter=html
      # - name: Run for the new tab
      #   run: npx playwright test demoNewTab.spec.ts --reporter=html